### ISSUE TITLE
Server crashes when interacting with Enchanting Table

### ISSUE THREAD

**Issue by AlphaKR93** [PlazmaMC/PlazmaBukkit#90]
Scrapped from official support discord (https://discord.com/channels/1083716853928558652/1202985544439570522)

```
[22:10:07 WARN]: Can't keep up! Is the server overloaded? Running 2749ms or 54 ticks behind
[22:10:24 WARN]: Can't keep up! Is the server overloaded? Running 2879ms or 57 ticks behind
2024-02-02 22:11:02,628 Log4j2-AsyncAppenderEventDispatcher-1-Async ERROR An exception occurred processing Appender rewrite org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.world.level.block.entity.TileEntityEnchantTable
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:165)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatch(AsyncAppenderEventDispatcher.java:130)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:92)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:74)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.world.level.block.entity.TileEntityEnchantTable
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:375)
        at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateStacktrace(StacktraceDeobfuscator.java:71)
        at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:37)
        at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:40)
        at io.papermc.paper.logging.StacktraceDeobfuscatingRewritePolicy.deobfuscateThrowable(StacktraceDeobfuscatingRewritePolicy.java:54)
        at io.papermc.paper.logging.StacktraceDeobfuscatingRewritePolicy.rewrite(StacktraceDeobfuscatingRewritePolicy.java:44)
        at org.apache.logging.log4j.core.appender.rewrite.RewriteAppender.append(RewriteAppender.java:81)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
        ... 6 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "ServerMain"]
        at net.minecraft.world.level.block.entity.TileEntityEnchantTable.<clinit>(TileEntityEnchantTable.java:25)
        at net.minecraft.world.level.block.BlockEnchantmentTable.a(BlockEnchantmentTable.java:85)
        at
ca.spottedleaf.dataconverter.minecraft.versions.V704.<clinit>(V704.java:201)
        at ca.spottedleaf.dataconverter.minecraft.datatypes.MCTypeRegistry.registerAll(MCTypeRegistry.java:86)
        at ca.spottedleaf.dataconverter.minecraft.datatypes.MCTypeRegistry.<clinit>(MCTypeRegistry.java:47)
        at net.minecraft.world.level.storage.Convertable.dank(Convertable.java:309)
        at net.minecraft.world.level.storage.Convertable.a(Convertable.java:297)
        at net.minecraft.world.level.storage.Convertable$ConversionSession.b(Convertable.java:596)
        at net.minecraft.world.level.storage.Convertable$ConversionSession.f(Convertable.java:587)
        at net.minecraft.server.Main.main(Main.java:226)
        at org.bukkit.craftbukkit.Main.main(Main.java:348)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
        at java.base/java.lang.Thread.run(Thread.java:840)

[22:11:02 INFO]: Stopping server
```

**Comment by AlphaKR93** [comment]
Fixed at 03821dffe9367c91673adab32ea10a52bdcc9a50
